### ISSUE TITLE
Enable Fortran

### ISSUE THREAD

**Issue by mdpiper** [conda-forge/cgns-feedstock#5]
Issue:

Fortran support was disabled in building `cgns=3.4.0`, but may be needed by users in the community. See discussion in #4.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by whophil** [comment]
Just checking in on the status of this. It seems like the latest recipe for `4.1.2` still has Fortran disabled.
